<h1>WST-Facebook SampleApp</h1>

<p>
	Hello <fb:name uid="<?php echo $this->fbuserid ?>" />, thanks for checking out the WST-Facebook SampleApp. You can findout more at <a href="http://wirsindthomas.com/wst-facebook/">wirsindthomas.com/wst-facebook</a>.
</p>
<p>
	For demonstration purposes, this is how you echo parameters which have been passed to the view object: <strong><?php echo $this->example_value ?></strong>
</p>
